[🚧] TNO-2075: Goodbye nest, and each feature to have its own store
bcgov/tno pull request #1275
Opened 2023-11-25 00:05 UTC by jdtoombs

Draft while I continue to regression test, few things to clean up still.. 

- Ripping out models that were associated with NEST
- Changing all `findContent()` to `findContentWithElasticSearch`
- Add filter store for each feature to maintain state independent of each other

Still need to:
- store returned content so page doesn't have to refetch each time
- add .catch to various places I forgot
- little bit more testing

The jist of it is here though.. will leave further commits separate for easy viewing.

2023-11-28 18:10 UTC, jdtoombs commented
@Fosol - just need to publish but this is ready for review

2023-11-28 23:31 UTC, Fosol requested changes

2023-11-28 23:31 UTC, Fosol commented on app/editor/yarn.lock
> +    tno-core: 0.0.372
Your lock file is pointing to a different version than the package.

2023-11-28 23:31 UTC, Fosol commented on app/subscriber/yarn.lock
> +    tno-core: 0.0.372
same issue here

2023-11-29 00:03 UTC, Fosol approved these changes

2023-11-29 00:03 UTC, merged