fix: #tno-2564 - switched from EmailTo being a string array
bcgov/tno pull request #1729
Opened 2024-04-19 18:55 UTC by kylgarmor

- switch ed to just a plain string which should be in CSV format
- array is parsed where neccesary
- switch all YAML from using an array index for the SERVICE_MAILTO value

2024-04-19 19:08 UTC, Fosol approved these changes
You'll need to manually update the various DeployConfig and ConfigMap in DEV and TEST.

2024-04-19 23:07 UTC, kylgarmor commented
> You'll need to manually update the various DeployConfig and ConfigMap in DEV and TEST.

Yup, I'm going to rope you in to help ;)

2024-04-22 22:10 UTC, Fosol requested changes

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/capture/base/deploy.yaml
> +                  name: transcription-service
capture?

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/clip/base/deploy.yaml
> +                  name: transcription-service
clip?

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/content/base/deploy.yaml
> +                  name: transcription-service
content?

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/contentmigration/base/deploy.yaml
> +                  name: transcription-service
contentmigration?

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/filecopy/base/deploy.yaml
> +                  name: transcription-service
filecopy?

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/indexing/base/deploy.yaml
> +                  name: transcription-service
indexing?

2024-04-22 22:10 UTC, Fosol commented on openshift/kustomize/services/syndication/base/deploy.yaml
> +                  name: transcription-service
syndication?

2024-04-23 00:00 UTC, Fosol approved these changes

2024-04-23 19:04 UTC, Fosol approved these changes
Much easier to maintain

2024-04-23 19:04 UTC, Fosol commented on openshift/kustomize/services/content/base/deploy.yaml
> +            - name: Service__UnpublishedIndex
Thanks for fixing this

2024-04-23 19:04 UTC, Fosol commented on openshift/kustomize/shared_resources/base/pvc.yaml
> +# ---
Is this removed for a reason?  Don't we need this for the various Ingest Services?

2024-04-23 21:42 UTC, merged