Admin Areas
bcgov/tno pull request #194
Opened 2022-07-26 17:22 UTC by jdtoombs

Adding a number of administrative area management pages.

Wondering if I should maybe combine some of these models/services/filters or if they are going to be customized further in the future.

2022-07-26 17:49 UTC, sturufous approved these changes

2022-07-27 22:05 UTC, Fosol requested changes

2022-07-27 22:05 UTC, Fosol commented on app/editor/src/features/admin/actions/constants/defaultAction.ts
> +export const defaultAction: IMediaTypeModel = {
Shouldn't this be a `IActionModel`?

2022-07-27 22:05 UTC, Fosol commented on app/editor/src/features/admin/categories/constants/defaultCategory.ts
> +export const defaultCategory: IMediaTypeModel = {
Shouldn't this be a `ICategoryModel`?

2022-07-27 22:05 UTC, Fosol commented on app/editor/src/features/admin/series/constants/defaultSeries.ts
> +export const defaultSeries: IMediaTypeModel = {
Shouldn't this be a `ISeriesModel`?

2022-07-27 22:05 UTC, Fosol commented on app/editor/src/features/admin/tags/constants/defaultTag.ts
> +export const defaultTag: IMediaTypeModel = {
Shouldn't this be a `ITagModel`?

2022-08-02 17:33 UTC, Fosol requested changes

2022-08-02 17:33 UTC, Fosol commented on api/net/Areas/Admin/Controllers/CategoryController.cs
> +    [ProducesResponseType(typeof(CategoryModel), (int)HttpStatusCode.OK)]
This should be an array or `IEnumerable` as we don't return a single `CategoryModel`

2022-08-02 17:33 UTC, Fosol commented on api/net/Areas/Admin/Controllers/SeriesController.cs
> +    [ProducesResponseType(typeof(SeriesModel), (int)HttpStatusCode.OK)]
This should be an array or `IEnumerable` as we don't return a single `SeriesModel`

2022-08-02 17:33 UTC, Fosol commented on api/net/Areas/Admin/Controllers/TagController.cs
> +    [ProducesResponseType(typeof(IPaged<TagModel>), (int)HttpStatusCode.OK)]
This should be an array or `IEnumerable` as we don't return a a page of `TagModel`

2022-08-02 20:48 UTC, Fosol approved these changes

2022-08-02 20:48 UTC, merged