TNO-2867 Avoid undefined of publishedOn, tno-core update
bcgov/tno pull request #2003
Opened 2024-07-03 20:18 UTC by kkwangsir

This change requires to bump tno-core 

Modify the logic of URL generation, if `publishedOn` is null or undefined, we shouldn't append any query string, and the old way gives an undefined follow by ` includeContent=true`

![image](https://github.com/bcgov/tno/assets/35620699/64b2abee-584b-45da-9362-bf066ab3be37)

2024-07-04 23:31 UTC, jdtoombs approved these changes

2024-07-05 17:04 UTC, jdtoombs commented
@kkwangsir - Hey, I published `tno-core 0.1.97`, you'll just have to update your package.json's in the editor and subscriber with the new version number!

2024-07-05 17:07 UTC, Fosol approved these changes

2024-07-05 17:08 UTC, Fosol requested changes
Update with latest tno-core version published by Jonny

2024-07-05 17:35 UTC, Fosol commented
Going to close so that I can create a new PR and get this out now.

2024-07-05 17:35 UTC, closed without merging