TNO-2907 Add status to disable send
bcgov/tno pull request #2089
Opened 2024-07-26 19:07 UTC by fbarreta

![image](https://github.com/user-attachments/assets/61c19554-11e5-4185-8f5d-e85bc38d604c)

This logic, disables the send in case the instance is already accepted, so it wouldn't make sense to re-send it.
Once you unblock or start the new report, the you would be able to send again, and the send flow isn't blocked on the "Submitted" status.

2024-07-26 19:36 UTC, Fosol commented
I don't think we want to block the ability to resend.   There is technically wrong with sending a report again, although subscribers would receive multiple copies.

2024-07-26 23:01 UTC, fbarreta commented
> I don't think we want to block the ability to resend. There is technically wrong with sending a report again, although subscribers would receive multiple copies.

The main issue was on the status not being updated on resend, and then getting locked. The change on the service will do it.

2024-07-28 22:54 UTC, Fosol requested changes

2024-07-29 17:52 UTC, closed without merging

2024-07-29 17:53 UTC, fbarreta commented
Changes on service addressed this error.
This won't be necessary anymore.