add image service
bcgov/tno pull request #230
Opened 2022-08-24 23:39 UTC by AlessiaYChen

2022-08-25 03:05 UTC, Fosol requested changes

2022-08-25 03:05 UTC, Fosol commented on services/net/image/ImageAction.cs
> +                            tasks.Add(CopyImage(client, manager.DataSource, file.Name));
My recommendation is to not bother with creating multiple threads at this point.

2022-08-25 03:05 UTC, Fosol commented on services/net/image/ImageAction.cs
> +    private string MappingImageFile(DataSourceModel dataSource)
This isn't ideal.  If we need to match a data source with an image naming convention.  Either the data source `Code` should be appropriate, or the `DataSource.Connection` should contain a relevant configuration value.

2022-08-25 03:05 UTC, Fosol commented on services/net/image/appsettings.json
> +    "HostName": "scharnhorst.tno.gov.bc.ca",
I wouldn't include the `HostName` or `UserName` in the default config values.  They're only for local testing.

2022-08-25 23:40 UTC, AlessiaYChen commented on services/net/image/ImageAction.cs
> +                            tasks.Add(CopyImage(client, manager.DataSource, file.Name));
add await for each CopyImage task

2022-08-26 22:56 UTC, Fosol approved these changes

2022-08-29 16:42 UTC, merged