WYSIWYG Bugs - Part 1/2
bcgov/tno pull request #413
Opened 2022-11-23 01:12 UTC by jdtoombs

- Fix tag invalid tags bug, now only checks last set of []
- Add a clear button to get rid of all text/html
- iOS compatible

2022-11-23 01:58 UTC, Fosol requested changes

2022-11-23 01:58 UTC, Fosol commented on app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
> +  const htmlMatch = /<.*?>/g;
remove if not needed

2022-11-24 07:45 UTC, jdtoombs commented on app/editor/src/components/form/wysiwyg/Wysiwyg.tsx
> +  const htmlMatch = /<.*?>/g;
done!

2022-11-25 15:54 UTC, Fosol approved these changes

2022-11-25 15:54 UTC, merged