TNO-899: Persist filter on refresh
bcgov/tno pull request #523
Opened 2023-02-09 21:38 UTC by jdtoombs

- ticket was to solve the toggle options persisting on refresh
- also covered the other fields
- remove productId and replace with productIds
- remove ContentFilter.tsx as it is not used anymore (is that ok?)

2023-02-10 15:59 UTC, jdtoombs commented on app/editor/src/features/content/list-view/utils/queryToFilter.ts
> +      productIds: search.productIds
Will remove this.

2023-02-10 16:04 UTC, Fosol commented on app/editor/src/features/content/tool-bar/sections/filter/AdvancedSearchSection.tsx
> +              value={sourceOptions.find((s) => s.label === filterAdvanced.searchTerm)}
This looks like a bug to me.  It should be the value of an option that is selected, not the label.

2023-02-10 18:14 UTC, jdtoombs commented on app/editor/src/features/content/list-view/interfaces/IContentListFilter.ts
>    productId: number;
Gonna leave this PR up rather than making another ticket for getting the productIds working. Converting to draft!

2023-02-17 15:14 UTC, Fosol requested changes

2023-02-17 15:14 UTC, Fosol commented on app/editor/src/features/content/list-view/utils/queryToFilter.ts
> +            .map((item: string) => Number(item.split('=')[1]))
This will throw an error if everything isn't perfect (i.e. `productIds=1&productionIds=`).  Use `URLSearchParams.getAll()`

2023-02-17 15:14 UTC, Fosol commented on app/editor/src/features/content/tool-bar/ContentToolBar.tsx
> +  const extractProductIds = (search: string) => {
You now have two places doing the exact same complex code that will throw an error if anything is out of place.  Use a utility function that uses existing features in javascript `URLSearchParams.getAll()`.

2023-02-17 20:48 UTC, Fosol approved these changes

2023-02-17 20:48 UTC, merged