TNO-821: New tag input
bcgov/tno pull request #587
Opened 2023-03-03 00:01 UTC by jdtoombs

Will be putting into draft for now as I have to test it with the new layout after my existing PR is merged. Also need to add this new component to the transcription tab.
<hr />

This PR includes:
- new tag component that will extract pattern matched tags from the WYSIWYG into a react-select component
- user may enter them via the WYSIWYG or by selecting from the dropdown
- a show list button has been added for a table reference including the full names of tags
- the user may position the table wherever they like when it is opened

![new-tags](https://user-images.githubusercontent.com/15724124/222594062-faafb471-4d40-4103-83b2-770599b588aa.gif)

2023-03-03 18:01 UTC, Fosol approved these changes

2023-03-03 19:42 UTC, jdtoombs commented
Good to go now 😄 @Fosol

2023-03-03 22:48 UTC, Fosol requested changes

2023-03-03 22:48 UTC, Fosol commented on app/editor/package.json
> +    "react-draggable": "^4.4.5",
Don't use ranges on the app, it causes issues later on

2023-03-03 23:29 UTC, jdtoombs commented
updated again @Fosol

2023-03-06 15:03 UTC, Fosol approved these changes

2023-03-06 15:03 UTC, merged