TNO-1304: Table hover bug
bcgov/tno pull request #759
Opened 2023-05-27 04:41 UTC by jdtoombs

**Blocked by my other PR as I will have to update the NPM package but putting this up for review.**

Seems to have been some CSS that we don't need but wanted to confirm with you @Fosol. Rows still signify hover over but got rid of that weird behaviour from hovering the Group Title.

2023-05-29 13:56 UTC, Fosol requested changes
I think you're waiting until your other PR is merged before publishing a new package.

2023-05-29 13:56 UTC, Fosol commented on app/subscriber/tno-core-0.0.249.tgz
Delete

2023-05-29 13:56 UTC, Fosol commented on app/subscriber/package.json
> +    "tno-core": "./tno-core-0.0.249.tgz"
Fix

2023-05-31 20:04 UTC, jdtoombs commented
@Fosol - updated

2023-05-31 21:49 UTC, Fosol approved these changes

2023-05-31 21:49 UTC, merged