TNO-1133: Front pages
bcgov/tno pull request #808
Opened 2023-06-07 23:15 UTC by jdtoombs

This PR Includes the feature that will display todays 5 front pages in the box located on the lower right hand side of the landing screen.

2023-06-07 23:16 UTC, jdtoombs commented on libs/net/dal/Services/ContentService.cs
> +    public IPaged<Content> FindFrontPages(bool asNoTracking = true)
Is this overkill?

2023-06-08 03:11 UTC, Fosol requested changes

2023-06-08 03:11 UTC, Fosol commented on libs/net/dal/Services/ContentService.cs
> +    public IPaged<Content> FindFrontPages(bool asNoTracking = true)
Use Elasticsearch not the database.

2023-06-09 23:12 UTC, Fosol requested changes
I've also published `tno-core:0.0.259`.  You'll need to publish a new version.

2023-06-14 05:13 UTC, jdtoombs commented
@Fosol - this PR has been updated

2023-06-14 13:50 UTC, Fosol approved these changes

2023-06-14 13:50 UTC, Fosol commented on libs/net/dal/Services/ContentService.cs
> +         var response = await _client.SearchAsync<API.Areas.Services.Models.Content.ContentModel>(s =>
Not a big deal, but you chose to use the NEST library instead of sending a raw JSON request.

2023-06-14 13:50 UTC, merged